// This file is auto-generated by @tanstack/router-plugin at dev/build time.
// Do not edit manually — run `npm run dev` or `npm run build` to regenerate.

import { Route as rootRoute } from './routes/__root';
import { Route as IndexRoute } from './routes/index';
import { Route as LogsRoute } from './routes/logs';

const rootTree = rootRoute.addChildren([
  IndexRoute,
  LogsRoute,
]);

export const routeTree = rootTree;

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    '/logs': {
      id: '/logs';
      path: '/logs';
      fullPath: '/logs';
      preLoaderRoute: typeof LogsRoute;
      parentRoute: typeof rootRoute;
    };
  }
}
